# Generated by Django 5.2.17 on 2026-09-30 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sorting', '0002_alter_fabricstock_stock_alter_sortingsession_fabric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('DRYING_OUTPUT', 'Drying output'), ('DISPATCH', 'Dispatch'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveBigIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='sorting.fabricstock')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['fabric', 'created_at'], name='inventory_s_fabric__2e0ba1_idx'), models.Index(fields=['source_type', 'source_id'], name='inventory_s_source__18ec1c_idx')],
            },
        ),
    ]
