# Generated by Django 5.2.17 on 2026-10-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_backfill_movements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('DRYING_OUTPUT', 'Drying output'), ('DISPATCH', 'Dispatch'), ('ADJUSTMENT', 'Adjustment'), ('SALES_RETURN', 'Sales return')], max_length=20),
        ),
    ]
