# Generated by Django 5.2.17 on 2026-09-29 20:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('warehouse_supervisor', 'Warehouse Supervisor'), ('sorting_supervisor', 'Sorting Supervisor'), ('decolorization_supervisor', 'Decolorization Supervisor'), ('drying_supervisor', 'Drying Supervisor')], max_length=50),
        ),
    ]
