# Generated by Django 5.2.17 on 2026-10-01 22:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decolorization', '0002_alter_chemicalissuance_chemical_and_more'),
        ('sorting', '0002_alter_fabricstock_stock_alter_sortingsession_fabric_and_more'),
        ('warehouse', '0003_supplier_profile_and_po_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'bills of materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Usual position in the process')),
                ('module', models.CharField(blank=True, choices=[('', 'None'), ('sorting', 'Sorting'), ('decolorization', 'Decolorization'), ('drying', 'Drying')], default='', help_text='The module whose sessions do this work, if any', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('quantity_per_100kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Rs. per unit', max_digits=12)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.billofmaterials')),
                ('chemical', models.ForeignKey(blank=True, help_text='Set for chemicals, to check stock', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='decolorization.chemicalstock')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('planned_input_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('planned_output_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('planned_start', models.DateField()),
                ('planned_end', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Released', 'Released'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('actual_output_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='production.billofmaterials')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to=settings.AUTH_USER_MODEL)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='sorting.fabricstock')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.factoryunit')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='production.routing')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Skipped', 'Skipped')], default='Pending', max_length=15)),
                ('machine', models.CharField(blank=True, default='', max_length=100)),
                ('planned_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('input_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('output_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('waste_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_steps', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_steps', to='production.processstage')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productionorder')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('chemical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_uses', to='decolorization.chemicalstock')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.productionorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('planned_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Labour and machine cost, Rs. per hour', max_digits=12)),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.routing')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_steps', to='production.processstage')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
    ]
