# Generated by Django 5.2.17 on 2026-10-01 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sorting', '0002_alter_fabricstock_stock_alter_sortingsession_fabric_and_more'),
        ('warehouse', '0003_supplier_profile_and_po_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('stage', models.CharField(choices=[('Incoming', 'Incoming material'), ('In-process', 'In-process'), ('Finished', 'Finished product')], max_length=20)),
                ('material_type', models.CharField(blank=True, default='', help_text='Leave empty to use for any material', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['stage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20)),
                ('stage', models.CharField(choices=[('Incoming', 'Incoming material'), ('In-process', 'In-process'), ('Finished', 'Finished product')], max_length=20)),
                ('inspected_on', models.DateField()),
                ('sample_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('composition', models.CharField(blank=True, default='', help_text='Fabric composition found, e.g. 80% cotton / 20% polyester', max_length=255)),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Conditional', 'Conditional'), ('Fail', 'Fail')], max_length=15)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(blank=True, help_text='The fabric lot (in-process and finished)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='sorting.fabricstock')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(blank=True, help_text='The delivery (incoming inspections)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='warehouse.stock')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='quality.qualitystandard')),
            ],
            options={
                'ordering': ['-inspected_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Corrective', 'Corrective'), ('Preventive', 'Preventive')], default='Corrective', max_length=12)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Done', 'Done')], default='Open', editable=False, max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completion_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_actions', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='quality.inspection')),
            ],
            options={
                'ordering': ['-status', 'due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('Measure', 'Measurement'), ('Pass/Fail', 'Pass / fail')], default='Measure', max_length=10)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('passed', models.BooleanField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.inspection')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StandardCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('Measure', 'Measurement'), ('Pass/Fail', 'Pass / fail')], default='Measure', max_length=10)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='quality.qualitystandard')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['result', 'released_at'], name='quality_ins_result_634a45_idx'),
        ),
    ]
