# Generated by Django 5.2.17 on 2026-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('threshold_label', models.CharField(blank=True, default='', max_length=120)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('send_email', models.BooleanField(default=False, help_text='Include in the e-mail digest')),
                ('escalate_after_days', models.PositiveIntegerField(blank=True, help_text='Days an item may stay open before it is marked as escalated', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
