# Generated by Django 5.2.17 on 2026-10-02 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sorting', '0002_alter_fabricstock_stock_alter_sortingsession_fabric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('recovery_rate', 'Recovery rate %'), ('landfill_share', 'Waste to landfill %'), ('water_per_kg', 'Water per kg (litres)'), ('energy_per_kg', 'Energy per kg (kWh)'), ('chemical_per_kg', 'Chemical cost per kg (Rs.)')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(choices=[('At least', 'At least'), ('At most', 'At most')], max_length=10)),
                ('period', models.CharField(blank=True, default='', help_text='e.g. 2026', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['metric', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('classification', models.CharField(choices=[('Recyclable', 'Recyclable'), ('Reusable', 'Reusable'), ('Hazardous', 'Hazardous'), ('General', 'General / landfill')], default='General', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'waste categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('utility', models.CharField(choices=[('Water', 'Water'), ('Electricity', 'Electricity'), ('Gas', 'Gas'), ('Steam', 'Steam'), ('Diesel', 'Diesel')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(editable=False, max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stage', models.CharField(blank=True, choices=[('Warehouse', 'Warehouse'), ('Sorting', 'Sorting'), ('Decolorization', 'Decolorization'), ('Drying', 'Drying'), ('Other', 'Other')], default='', help_text='Leave empty for the whole factory', max_length=20)),
                ('meter_reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('stage', models.CharField(choices=[('Warehouse', 'Warehouse'), ('Sorting', 'Sorting'), ('Decolorization', 'Decolorization'), ('Drying', 'Drying'), ('Other', 'Other')], default='Other', max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disposal_method', models.CharField(choices=[('Recycled internally', 'Recycled internally'), ('Sold as by-product', 'Sold as by-product'), ('Sent to recycler', 'Sent to recycler'), ('Reused', 'Reused'), ('Landfill', 'Landfill'), ('Incinerated', 'Incinerated'), ('Treated', 'Treated')], max_length=30)),
                ('disposed_to', models.CharField(blank=True, default='', help_text='Who took the waste, e.g. a recycler or a buyer', max_length=255)),
                ('disposal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Money received when the waste was sold as a by-product', max_digits=14)),
                ('disposal_reference', models.CharField(blank=True, default='', help_text='Manifest or gate pass number', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='sustainability.wastecategory')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records', to='sorting.fabricstock')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
