# Generated by Django 5.2.12 on 2026-03-28 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_type', models.CharField(max_length=100)),
                ('vendor_weight_slip', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('our_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unloading_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Received', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.factoryunit')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.vendor')),
            ],
        ),
    ]
