# Generated by Django 5.2.17 on 2026-10-01 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('warehouse', '0002_alter_stock_unit_alter_stock_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='po_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='procurement.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(blank=True, choices=[('Textile waste', 'Textile waste'), ('Post-consumer', 'Post-consumer'), ('Pre-consumer', 'Pre-consumer'), ('Chemicals', 'Chemicals'), ('Packaging', 'Packaging'), ('Other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='specialties',
            field=models.CharField(blank=True, default='', help_text='Materials this supplier deals in, e.g. "cotton, denim"', max_length=255),
        ),
    ]
