# Generated by Django 5.2.12 on 2026-03-28 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=255)),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sorted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('In Warehouse', 'In Warehouse'), ('In Sorting', 'In Sorting'), ('Sorted', 'Sorted'), ('Sent to Decolorization', 'Sent to Decolorization')], default='In Warehouse', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_stocks', to='warehouse.stock')),
            ],
        ),
        migrations.CreateModel(
            name='SortingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('quantity_taken', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_sorted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('waste_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='In Progress', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorting_sessions', to='sorting.fabricstock')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorting_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
