# Generated by Django 5.2.17 on 2026-09-29 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0001_initial'),
        ('warehouse', '0002_alter_stock_unit_alter_stock_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabric_stocks', to='warehouse.stock'),
        ),
        migrations.AlterField(
            model_name='sortingsession',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorting_sessions', to='sorting.fabricstock'),
        ),
        migrations.AlterField(
            model_name='sortingsession',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorting_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
