# Generated by Django 5.2.17 on 2026-09-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete (Soft)'), ('RESTORE', 'Restore'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Failed login'), ('EXPORT', 'Export')], max_length=20),
        ),
    ]
