# Generated by Django 5.2.17 on 2026-10-02 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decolorization', '0003_chemical_extras'),
        ('drying', '0002_alter_dryingsession_dryer_alter_dryingsession_fabric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, default='', help_text='e.g. Sorting line, Tank, Dryer, Baler, Shredder, Utility', max_length=60)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('serial_number', models.CharField(blank=True, default='', max_length=120)),
                ('specifications', models.TextField(blank=True, default='')),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Idle', 'Idle'), ('Under maintenance', 'Under maintenance'), ('Broken down', 'Broken down'), ('Retired', 'Retired')], default='Running', max_length=20)),
                ('hourly_operating_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dryer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='drying.dryer')),
                ('tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='decolorization.tank')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=150)),
                ('every_days', models.PositiveIntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, help_text='First due date, until the task is done once')),
                ('last_done_on', models.DateField(blank=True, null=True)),
                ('next_due_on', models.DateField(editable=False)),
                ('instructions', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='maintenance.machine')),
            ],
            options={
                'ordering': ['next_due_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20)),
                ('kind', models.CharField(choices=[('Preventive', 'Preventive'), ('Corrective', 'Corrective')], default='Corrective', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Open', max_length=12)),
                ('is_breakdown', models.BooleanField(default=False, help_text='The machine stopped unexpectedly')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('downtime_minutes', models.PositiveIntegerField(default=0, help_text='How long the machine was stopped')),
                ('labour_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('work_done', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.machine')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_work_orders', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.maintenanceschedule')),
            ],
            options={
                'ordering': ['-reported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='maintenance.sparepart')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='maintenance.workorder')),
            ],
            options={
                'verbose_name': 'part used',
                'verbose_name_plural': 'parts used',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'reported_at'], name='maintenance_status_62844d_idx'),
        ),
    ]
