# Generated by Django 5.2.17 on 2026-09-29 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drying', '0001_initial'),
        ('sorting', '0002_alter_fabricstock_stock_alter_sortingsession_fabric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryingsession',
            name='dryer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drying_sessions', to='drying.dryer'),
        ),
        migrations.AlterField(
            model_name='dryingsession',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drying_sessions', to='sorting.fabricstock'),
        ),
        migrations.AlterField(
            model_name='dryingsession',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drying_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
