# Generated by Django 5.2 on 2026-04-10 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decolorization', '0001_initial'),
        ('sorting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dryer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dryer_type', models.CharField(choices=[('Tumble', 'Tumble Dryer'), ('Conveyor', 'Conveyor Belt Dryer'), ('Chamber', 'Chamber Dryer')], default='Tumble', max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Running', 'Running'), ('Cooling', 'Cooling'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DryingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_quantity', models.DecimalField(decimal_places=2, help_text='kg received wet from decolorization', max_digits=10)),
                ('output_quantity', models.DecimalField(decimal_places=2, default=0, help_text='kg after drying (weight loss expected ~8-15%)', max_digits=10)),
                ('waste_quantity', models.DecimalField(decimal_places=2, default=0, help_text='kg discarded (damaged, contaminated during drying)', max_digits=10)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, help_text='Operating temperature in °C', max_digits=5, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Total drying duration in minutes', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('On Hold', 'On Hold')], default='Pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decolor_session', models.ForeignKey(blank=True, help_text='Decolorization session this batch originated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drying_sessions', to='decolorization.decolorizationsession')),
                ('dryer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drying_sessions', to='drying.dryer')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drying_sessions', to='sorting.fabricstock')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drying_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
