# Generated by Django 5.2.17 on 2026-10-02 15:36

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'document categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_number', models.CharField(blank=True, default='', help_text='The number printed on the document, e.g. a certificate number', max_length=100)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('linked_type', models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Purchase order', 'Purchase order'), ('Customer', 'Customer'), ('Sales order', 'Sales order'), ('Invoice', 'Invoice'), ('Fabric lot', 'Fabric lot'), ('Production order', 'Production order'), ('Inspection', 'Inspection'), ('Chemical', 'Chemical'), ('Employee', 'Employee'), ('Machine', 'Machine'), ('Other', 'Other')], default='', max_length=20)),
                ('linked_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('linked_label', models.CharField(blank=True, default='', max_length=200)),
                ('current_version', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('file', models.FileField(max_length=120, upload_to=apps.documents.models.upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=10)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', help_text='What changed in this version', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['linked_type', 'linked_id'], name='documents_d_linked__333f07_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expires_on'], name='documents_d_expires_9dafc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='unique_document_version'),
        ),
    ]
