# Generated by Django 5.2.12 on 2026-03-28 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sorting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(max_length=255)),
                ('total_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(default='Liters', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('tank_status', models.CharField(choices=[('Empty', 'Empty'), ('Filled', 'Filled'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cleaning', 'Cleaning')], default='Empty', max_length=50)),
                ('fabric_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expected_completion', models.DateTimeField(blank=True, null=True)),
                ('actual_completion', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanks', to='sorting.fabricstock')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DecolorizationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('output_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('waste_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('On Hold', 'On Hold')], default='In Progress', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decolorization_sessions', to='sorting.fabricstock')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decolorization_sessions', to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='decolorization.tank')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_issuances', to=settings.AUTH_USER_MODEL)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='decolorization.chemicalstock')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_issuances', to='decolorization.tank')),
            ],
        ),
    ]
