# Generated by Django 5.2.17 on 2026-09-29 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decolorization', '0001_initial'),
        ('sorting', '0002_alter_fabricstock_stock_alter_sortingsession_fabric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalissuance',
            name='chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='decolorization.chemicalstock'),
        ),
        migrations.AlterField(
            model_name='chemicalissuance',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_issuances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chemicalissuance',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_issuances', to='decolorization.tank'),
        ),
        migrations.AlterField(
            model_name='decolorizationsession',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decolorization_sessions', to='sorting.fabricstock'),
        ),
        migrations.AlterField(
            model_name='decolorizationsession',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decolorization_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decolorizationsession',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='decolorization.tank'),
        ),
    ]
