# Generated by Django 5.2.17 on 2026-10-02 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decolorization', '0002_alter_chemicalissuance_chemical_and_more'),
        ('warehouse', '0003_supplier_profile_and_po_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('material_type', models.CharField(blank=True, default='', help_text='Leave empty to use for any material', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='chemicalissuance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuances', to='decolorization.decolorizationsession'),
        ),
        migrations.AddField(
            model_name='chemicalissuance',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='chemicalstock',
            name='handling_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chemicalstock',
            name='hazard_class',
            field=models.CharField(blank=True, default='', help_text='e.g. Corrosive, Oxidizer', max_length=100),
        ),
        migrations.AddField(
            model_name='chemicalstock',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Only an admin may issue it'),
        ),
        migrations.AddField(
            model_name='chemicalstock',
            name='sds_reference',
            field=models.CharField(blank=True, default='', help_text='Where the safety data sheet is kept: a link or a file reference', max_length=255),
        ),
        migrations.AddField(
            model_name='chemicalstock',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemicals', to='warehouse.vendor'),
        ),
        migrations.AddField(
            model_name='chemicalstock',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rs. per unit of measure; receiving a lot updates it', max_digits=12),
        ),
        migrations.AddField(
            model_name='decolorizationsession',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decolorizationsession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decolorizationsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decolorizationsession',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='decolorizationsession',
            name='water_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('water_liters_per_100kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='What changed in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='decolorization.recipe')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_100kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='decolorization.chemicalstock')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='decolorization.recipeversion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='decolorizationsession',
            name='recipe_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='decolorization.recipeversion'),
        ),
        migrations.CreateModel(
            name='ChemicalLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('received_on', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='decolorization.chemicalstock')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_lots', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_lots', to='warehouse.vendor')),
            ],
            options={
                'ordering': ['-received_on', '-id'],
                'constraints': [models.UniqueConstraint(fields=('chemical', 'lot_number'), name='unique_chemical_lot')],
            },
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(fields=('recipe', 'version'), name='unique_recipe_version'),
        ),
    ]
