# Generated by Django 5.2.17 on 2026-09-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_backfill_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Online Transfer', 'Online Transfer')], default='Cash', max_length=50),
        ),
    ]
