# Generated by Django 5.2.17 on 2026-10-02 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_payment_method_online_transfer'),
        ('sorting', '0002_alter_fabricstock_stock_alter_sortingsession_fabric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('material_type', models.CharField(blank=True, default='', max_length=255)),
                ('grade', models.CharField(blank=True, default='', max_length=100)),
                ('specification', models.TextField(blank=True, default='')),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='List price; a customer category can have its own', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.CharField(blank=True, choices=[('Wholesaler', 'Wholesaler'), ('Manufacturer', 'Manufacturer'), ('Exporter', 'Exporter'), ('Retailer', 'Retailer'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = no limit. Going over it warns; it never blocks.', max_digits=14),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=0, help_text='Days an invoice may stay unpaid'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.product'),
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.salesorder')),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20)),
                ('fabric_quality', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Converted', 'Converted')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.customer')),
                ('fabric', models.ForeignKey(blank=True, help_text='The lot to sell from; can be chosen when the order is made', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sorting.fabricstock')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation', to='sales.salesorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20)),
                ('return_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('restock', models.BooleanField(default=False, help_text='Put the returned weight back into sellable stock')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Requested', max_length=20)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.salesorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_category', models.CharField(choices=[('Wholesaler', 'Wholesaler'), ('Manufacturer', 'Manufacturer'), ('Exporter', 'Exporter'), ('Retailer', 'Retailer'), ('Other', 'Other')], max_length=20)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sales.product')),
            ],
            options={
                'ordering': ['customer_category'],
                'constraints': [models.UniqueConstraint(fields=('product', 'customer_category'), name='unique_product_category_price')],
            },
        ),
    ]
