# Generated by Django 5.2.17 on 2026-10-02 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('page', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['role', 'page'],
                'constraints': [models.UniqueConstraint(fields=('role', 'page'), name='unique_role_page')],
            },
        ),
        migrations.CreateModel(
            name='UserPageOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50)),
                ('allowed', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'page'],
                'constraints': [models.UniqueConstraint(fields=('user', 'page'), name='unique_user_page_override')],
            },
        ),
    ]
